GET http://localhost:5000/miniaturas

###
GET http://localhost:5000/miniaturas?marca_id=1

###
GET http://localhost:5000/miniaturas/1

###
POST http://localhost:5000/miniaturas
Content-Type: application/json

{
  "modelo": "Porsche 911 GT3 RS",
  "escala": "1:24",
  "preco": 180.00,
  "marca_id": 1
}

###
PUT http://localhost:5000/miniaturas/1
Content-Type: application/json

{
  "modelo": "Nissan GT-R R35 Nismo",
  "escala": "1:64",
  "preco": 35.00,
  "marca_id": 1
}

###
DELETE http://localhost:5000/miniaturas/1
